on:
  schedule:
    - cron: "0 * * * *" # Every hour. Ref https://crontab.guru/examples.html
  workflow_dispatch:
name: Scrape Strom Erzeugung Data
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build
        run: npm install
      - name: Scrape
        run: npm run action
