name: Test downloa

# Controls when the action will run.
on:
  schedule:
    - cron:  "0 10 * * TUE"
  workflow_dispatch:


jobs:
  runscript:
    name: Example
    runs-on: ubuntu-latest
    steps:
      - name: Run wget
        run:  wget "https://transparency.apg.at/transparency-api/api/v1/Download/AGPT/German/M15/2021-01-01T000000/2022-09-26T000000/AGPT_2020-12-31T23_00_00Z_2022-09-26T22_00_00Z_60M_de_2022-09-26T15_40_08Z.csv" >> ${GITHUB_WORKSPACE}/test.csv
